
import javax.swing.ImageIcon;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANDREA
 */
public class Hotel extends javax.swing.JFrame {

    /**
     * Creates new form HOTELES
     */
    public Hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Hoteles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Plaza", "Gran Caribe", "Beach Resort", "Hotel Central", "Casa Blanca", "Royal Suites", "Grand Hyatt", "La Playa", "Hotel Andino", "Hotel de Ville" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 260, 70));

        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setText("Pais:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel6.setText("Precio:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 190, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 180, -1));

        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 80, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ANDREA\\Pictures\\EXPLOITIZ\\Hoteles B.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  String Hoteles  = (String) jComboBox1.getSelectedItem();
          
  switch (Hoteles){
      case "Hotel Plaza":
          ImageIcon imagen = new ImageIcon("plaza mexico.jpg");
          jLabel3.setIcon(imagen);
          jLabel3.setVisible(true);
          jTextField1.setText("Avenida Reforma 123");
          jTextField2.setText("Mexico");
          jTextField3.setText("$2500.50");
          jTextField4.setText("Lujo (5)");
           break;
                
          case "Gran Caribe":
          ImageIcon im = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(im);
          jLabel3.setVisible(true);
          jTextField1.setText("Calle 5ta Avenida, 45");
          jTextField2.setText("Gran Caribe,Cuba");
          jTextField3.setText("$3000.75");
          jTextField4.setText("Todo incluido (5)");
                  break;
          case "Beach Resort":
          ImageIcon a = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(a);
          jLabel3.setVisible(true);
          jTextField1.setText("Calle ");
          jTextField2.setText("República Dominicana ");
          jTextField3.setText("2200.00");
          jTextField4.setText("Todo incluido (5)");
          
                   break;
                   
          case "Hotel Central":
          ImageIcon b = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(b);
          jLabel3.setVisible(true);
          //txt1.setText("Hotel Central,España, Gran Vía 20, Madrid, Económico, 850.00");
                   break;
                   
          case"Casa Blanca":
          ImageIcon c = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(c);
          jLabel3.setVisible(true);
          //txt1.setText("Casa Blanca, Colombia, Carrera 7, Bogotá, Boutique, 1500.25");
                   break;
                   
          case"Royal Suites":
          ImageIcon d = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(d);
          jLabel3.setVisible(true);
          //txt1.setText("Royal Suites, Francia, Rue de la Paix 15, París, Lujo, 5000.00");
                   break;
                   
          case "Grand Hyatt":
          ImageIcon e = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(e);
          jLabel3.setVisible(true);
          //txt1.setText("Grand Hyatt, 'Estados Unidos, Park Avenue 7, Nueva York, Lujo, 3500.00");
                   break;
                   
                   
          case "La Playa":
          ImageIcon f = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(f);
          jLabel3.setVisible(true);
          //txt1.setText("La Playa, México, Playa del Carmen, Quintana Roo, Resort, 1800.80");
                   break;
                   
          case "Hotel Andino":
          ImageIcon g = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(g);
          jLabel3.setVisible(true);
          //txt1.setText("Hotel Andino, Chile, Av. Providencia 500, Santiago, Económico, 1100.00");
                   break;
                   
          case "Hotel de Ville":
          ImageIcon h = new ImageIcon("GRAN CARIBE.jpg");
          jLabel3.setIcon(h);
          jLabel3.setVisible(true);
          //txt1.setText("Hôtel de Ville, Suiza, Rue du Mont-Blanc 10, Ginebra, Lujo, 4500.60");
                   break;
  }
  
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
