package com.agencia.turismo.gui;

import com.agencia.turismo.service.AgregarCarrito;
import com.agencia.turismo.service.Hoteles;
import com.agencia.turismo.service.Ingresar;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.sql.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Hotel extends javax.swing.JFrame {
    Hoteles ht = new Hoteles();
    int id ;
    AgregarCarrito carrito = new AgregarCarrito();
    Date selectedDate;
    Date selectedDate2;
    String nameHotel;
    Ingresar login;
 
    public Hotel(int id) {
        this.id = id;
        initComponents();
    }
    
    public Hotel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CBHotel = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        BRegresar = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        BFechaReserva = new javax.swing.JButton();
        BFechaRegreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(812, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Hoteles");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        CBHotel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel Plaza", "Gran Caribe", "Beach Resort", "Hotel Central", "Casa Blanca", "Royal Suites", "Grand Hyatt", "La Playa", "Hotel Andino", "Hotel de Ville" }));
        CBHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBHotelActionPerformed(evt);
            }
        });
        getContentPane().add(CBHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 260, 70));

        jLabel4.setText("Direccion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel5.setText("Pais:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 360, 20));

        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 360, -1));
        getContentPane().add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 360, -1));

        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 360, -1));

        BRegresar.setBackground(new java.awt.Color(0, 0, 0));
        BRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BRegresar.setText("Regresar");
        BRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 120, 30));

        BAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 30));

        BFechaReserva.setText("FECHA DE RESERVA");
        BFechaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFechaReservaActionPerformed(evt);
            }
        });
        getContentPane().add(BFechaReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        BFechaRegreso.setText("FECHA DE REGRESO");
        BFechaRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFechaRegresoActionPerformed(evt);
            }
        });
        getContentPane().add(BFechaRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 810, 450));

        jLabel8.setText("Precio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel9.setText("Precio:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBHotelActionPerformed
       
        ht.setName();
        
        for(String name: ht.getName() ){
            CBHotel.addItem(name);
        }
        this.nameHotel = (String) CBHotel.getSelectedItem();
        tipo.setText(ht.getType(nameHotel));
        direccion.setText(ht.getAddress(nameHotel));
        pais.setText(ht.getCountry(nameHotel));
        precio.setText("$" + ht.getPrice(nameHotel) + " pesos");
        
    }//GEN-LAST:event_CBHotelActionPerformed

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionActionPerformed

    private void BRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegresarActionPerformed
        new Reserva(this.id).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BRegresarActionPerformed

    private void BFechaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFechaReservaActionPerformed
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("dd/MM/yyyy"); // Formato de la fecha
        dateChooser.setPreferredSize(new Dimension(200, 30)); // Tamaño del componente

        // Crear un JPanel para añadir el JDateChooser
        JPanel panel = new JPanel();
        panel.add(dateChooser);

        // Mostrar el JDateChooser en un JOptionPane
        int option = JOptionPane.showConfirmDialog(null, panel, "Selecciona una Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            // Obtener la fecha seleccionada directamente como java.sql.Date
            selectedDate = new Date(dateChooser.getDate().getTime()); // Convertir a java.sql.Date
            if (selectedDate != null) {
                // Mostrar la fecha seleccionada
                JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + selectedDate.toString());
            } else {
                JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fecha.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
        }

        // Usar la fecha fuera del bloque if
        if (selectedDate != null) {
            System.out.println("La fecha seleccionada es: " + selectedDate);
        } else {
            System.out.println("No se seleccionó ninguna fecha.");
        }
    }//GEN-LAST:event_BFechaReservaActionPerformed

    private void BFechaRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFechaRegresoActionPerformed
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("dd/MM/yyyy"); // Formato de la fecha
        dateChooser.setPreferredSize(new Dimension(200, 30)); // Tamaño del componente

        // Crear un JPanel para añadir el JDateChooser
        JPanel panel = new JPanel();
        panel.add(dateChooser);

        // Mostrar el JDateChooser en un JOptionPane
        int option = JOptionPane.showConfirmDialog(null, panel, "Selecciona una Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            // Obtener la fecha seleccionada directamente como java.sql.Date
            selectedDate2 = new Date(dateChooser.getDate().getTime()); // Convertir a java.sql.Date
            if (selectedDate2 != null) {
                // Mostrar la fecha seleccionada
                JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + selectedDate2.toString());
            } else {
                JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fecha.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
        }

        // Usar la fecha fuera del bloque if
        if (selectedDate2 != null) {
            System.out.println("La fecha seleccionada es: " + selectedDate2);
        } else {
            System.out.println("No se seleccionó ninguna fecha.");
        }
    }//GEN-LAST:event_BFechaRegresoActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        carrito.setId(this.id);
        carrito.setIdProducto("hotels", nameHotel);
        carrito.insertBookingHoteles(selectedDate,selectedDate2);
    }//GEN-LAST:event_BAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BFechaRegreso;
    private javax.swing.JButton BFechaReserva;
    private javax.swing.JButton BRegresar;
    private javax.swing.JComboBox<String> CBHotel;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pais;
    private javax.swing.JLabel precio;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
