package com.agencia.turismo.gui;

import com.agencia.turismo.service.AgregarCarrito;
import com.agencia.turismo.service.Ingresar;
import com.agencia.turismo.service.Tour;
import com.toedter.calendar.JDateChooser;
import java.awt.Dimension;
import java.sql.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class Tours extends javax.swing.JFrame {
Tour tour = new Tour();
int id; 
AgregarCarrito carrito = new AgregarCarrito();
Date selectedDate;
String nameTour;
Ingresar login;

    public Tours(int id) {
        initComponents();
        this.id = id;
        tour.setName();
        
        for (String name : tour.getName() ){
            CBTours.addItem(name);
        }
    }
    public Tours() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CBTours = new javax.swing.JComboBox<>();
        descripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BRegresar = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        destino = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        reservaFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(812, 450));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tours");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        CBTours.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CBTours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige el tour" }));
        CBTours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBToursActionPerformed(evt);
            }
        });
        getContentPane().add(CBTours, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 30));

        descripcion.setText("Descripcion:");
        getContentPane().add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 410, 270));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Duracion:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Destino:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Precio");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        BRegresar.setBackground(new java.awt.Color(0, 0, 0));
        BRegresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BRegresar.setText("Regresar");
        BRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        BAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BAgregar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BAgregar.setText("Agregar");
        BAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(BAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));
        getContentPane().add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 260, -1));
        getContentPane().add(destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 260, -1));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 160, -1));

        reservaFecha.setText("FECHA RESERVA");
        reservaFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaFechaActionPerformed(evt);
            }
        });
        getContentPane().add(reservaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CBToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBToursActionPerformed
        this.nameTour = (String) CBTours.getSelectedItem();
        descripcion.setText(tour.getDescription(nameTour));
        duracion.setText(tour.getDuration(nameTour));
        destino.setText(tour.getDestiny(nameTour));
        precio.setText("$" + tour.getPrice(nameTour) + " pesos");
    }//GEN-LAST:event_CBToursActionPerformed

    private void BRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegresarActionPerformed
       new Reserva(this.id).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_BRegresarActionPerformed

    private void reservaFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaFechaActionPerformed
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("yyyy/MM/dd"); // Formato de la fecha
        dateChooser.setPreferredSize(new Dimension(200, 30)); // Tamaño del componente

        // Crear un JPanel para añadir el JDateChooser
        JPanel panel = new JPanel();
        panel.add(dateChooser);

        // Mostrar el JDateChooser en un JOptionPane
        int option = JOptionPane.showConfirmDialog(null, panel, "Selecciona una Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.OK_OPTION) {
            // Obtener la fecha seleccionada directamente como java.sql.Date
            selectedDate = new Date(dateChooser.getDate().getTime()); // Convertir a java.sql.Date
            if (selectedDate != null) {
                // Mostrar la fecha seleccionada
                JOptionPane.showMessageDialog(null, "Fecha seleccionada: " + selectedDate.toString());
            } else {
                JOptionPane.showMessageDialog(null, "No se seleccionó ninguna fecha.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Operación cancelada.");
        }

        // Usar la fecha fuera del bloque if
        if (selectedDate != null) {
            System.out.println("La fecha seleccionada es: " + selectedDate);
        } else {
            System.out.println("No se seleccionó ninguna fecha.");
        }

    }//GEN-LAST:event_reservaFechaActionPerformed

    private void BAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAgregarActionPerformed
        carrito.setId(this.id);
        carrito.setIdProducto("tours", nameTour);
        carrito.insertBookingTours(selectedDate);
    }//GEN-LAST:event_BAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tours.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tours().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BRegresar;
    private javax.swing.JComboBox<String> CBTours;
    private javax.swing.JTextField descripcion;
    private javax.swing.JTextField destino;
    private javax.swing.JTextField duracion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField precio;
    private javax.swing.JButton reservaFecha;
    // End of variables declaration//GEN-END:variables
}
