/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agencia.turismo.gui;

import com.agencia.turismo.service.Vuelo;

/**
 *
 * @author Dana Gonzalez
 */
public class Vuelos extends javax.swing.JFrame {
Vuelo vuelo = new Vuelo();
    /**
     * Creates new form Vuelos
     */
    public Vuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBVuelos = new javax.swing.JComboBox<>();
        BRegresar = new javax.swing.JButton();
        BAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        tipoVuelo = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        destinoO = new javax.swing.JTextField();
        destinoF = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();

        jLabel1.setPreferredSize(new java.awt.Dimension(812, 250));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setText("Vuelos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        CBVuelos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CBVuelos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Airolinea"}));
        CBVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBVuelosActionPerformed(evt);
            }
        });
        getContentPane().add(CBVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 140, 30));

        BRegresar.setBackground(new java.awt.Color(0, 0, 0));
        BRegresar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BRegresar.setForeground(new java.awt.Color(255, 255, 255));
        BRegresar.setText("Regresar");
        BRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, -1, -1));

        BAgregar.setBackground(new java.awt.Color(0, 0, 0));
        BAgregar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BAgregar.setForeground(new java.awt.Color(255, 255, 255));
        BAgregar.setText("Agregar");
        getContentPane().add(BAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Pais:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Numero airolinea:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Destino origen");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Destino Final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Precio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Tipo de vuelo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 200, -1));
        getContentPane().add(tipoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, -1));
        getContentPane().add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 260, -1));
        getContentPane().add(destinoO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, -1));
        getContentPane().add(destinoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 260, -1));
        getContentPane().add(pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 220, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegresarActionPerformed
        new Reserva().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BRegresarActionPerformed

    private void CBVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBVuelosActionPerformed
       vuelo.setName();
        
        for (String name : vuelo.getName()){
            CBVuelos.addItem(name);
        }
        
        String nameTour = (String) CBVuelos.getSelectedItem();
        tipoVuelo.setText(vuelo.getType(nameTour));
        numero.setText(vuelo.getNumberAir(nameTour));
        destinoO.setText(vuelo.getOrigin(nameTour));
        destinoF.setText(vuelo.getEnd(nameTour));
        pais.setText(vuelo.getCountry(nameTour));
        precio.setText("$" + vuelo.getPrice(nameTour) + " pesos");
    }//GEN-LAST:event_CBVuelosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vuelos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vuelos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BRegresar;
    private javax.swing.JComboBox<String> CBVuelos;
    private javax.swing.JTextField destinoF;
    private javax.swing.JTextField destinoO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField tipoVuelo;
    // End of variables declaration//GEN-END:variables
}
